/**
 * render-slides: jobs/<job_id>/slides.json + images → jobs/<job_id>/slides/slide_N.png
 *
 * Renders each slide of a TikTok photo-slideshow concept to a 1080x1920 PNG via
 * the Remotion `Slide` composition (`remotion still`). Slide i uses img_i.png as
 * its background (generated by gen-images from the slide's image_prompt); if the
 * background is missing the Slide falls back to a gradient. Idempotent: skips a
 * slide whose PNG already exists.
 *
 * Per-slide text placement/style can be overridden by adding "position"
 * ("top"|"center"|"bottom") and "textStyle" ("white"|"black"|"plain") to a slide
 * object in slides.json; defaults are center + white plaque.
 *
 * Usage:
 *   npx tsx src/render-slides.ts <job_id> [--style white|black|plain] [--position top|center|bottom]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

type Slide = {
  text: string;
  image_prompt?: string;
  show_app?: boolean;
  position?: "top" | "center" | "bottom";
  textStyle?: "white" | "black" | "plain";
  /** background image filename in images/ (defaults to img_<n>.png by position) */
  img?: string;
  /** optional app screenshot (job-relative path) shown in an iPhone mockup */
  appShot?: string;
};
type Concept = { title?: string; slides: Slide[] };

export function renderSlides(
  jobId: string,
  defaults: { style?: "white" | "black" | "plain"; position?: "top" | "center" | "bottom" } = {}
): string[] {
  const jobDir = path.join("jobs", jobId);
  const slidesPath = path.join(jobDir, "slides.json");
  if (!existsSync(slidesPath)) throw new Error(`No slides.json: ${slidesPath}`);
  const concept = JSON.parse(readFileSync(slidesPath, "utf8")) as Concept;
  if (!concept.slides?.length) throw new Error("slides.json has no slides");

  const outDir = path.join(jobDir, "slides");
  mkdirSync(outDir, { recursive: true });
  const written: string[] = [];

  concept.slides.forEach((slide, i) => {
    const n = i + 1;
    const outPath = path.join(outDir, `slide_${n}.png`);
    if (existsSync(outPath)) {
      console.log(`[render-slides] skip (exists): slide_${n}.png`);
      written.push(outPath);
      return;
    }
    const imgFile = slide.img ?? `img_${n}.png`;
    const bg = existsSync(path.join(jobDir, "images", imgFile))
      ? `${jobId}/images/${imgFile}`
      : null;
    const appShot =
      slide.appShot && existsSync(path.join(jobDir, slide.appShot))
        ? `${jobId}/${slide.appShot}`
        : null;
    const props = {
      bg,
      text: slide.text,
      textStyle: slide.textStyle ?? defaults.style ?? "white",
      position: slide.position ?? defaults.position ?? "center",
      appShot,
    };
    const propsPath = path.join(outDir, `.props_${n}.json`);
    writeFileSync(propsPath, JSON.stringify(props));
    console.log(`[render-slides] rendering slide_${n}.png (bg=${bg ?? "gradient"}) ...`);
    execFileSync(
      "npx",
      ["remotion", "still", "Slide", outPath, `--props=${propsPath}`],
      { stdio: "inherit" }
    );
    written.push(outPath);
  });

  console.log(`[render-slides] done: ${written.length} slide(s) in ${outDir}`);
  return written;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const jobId = args[0];
  if (!jobId) {
    console.log(
      "Usage: tsx src/render-slides.ts <job_id> [--style white|black|plain] [--position top|center|bottom]"
    );
    process.exit(1);
  }
  const val = (f: string) => {
    const i = args.indexOf(f);
    return i >= 0 ? args[i + 1] : undefined;
  };
  try {
    renderSlides(jobId, {
      style: val("--style") as any,
      position: val("--position") as any,
    });
  } catch (e) {
    console.error("[render-slides] FAILED:", (e as Error).message);
    process.exit(1);
  }
}
